name: build-lammps-latest-release

on:
  push:
    branches: [ "master", "feature/github_actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout OCTP
      uses: actions/checkout@v4
      with:
        path: octp

    - name: Checkout LAMMPS latest stable_* tagged release
      uses: actions/checkout@v4
      with:
        repository: lammps/lammps
        ref: stable_23Jun2022_update4
        path: lammps

    - name: Copy OCTP files to LAMMPS src directory
      run: |
        cp --verbose octp/src/* lammps/src/

    - name: Install OpenMPI
      run: |
        sudo apt-get install openmpi-bin openmpi-common openmpi-doc libopenmpi-dev
        echo "mpi version"
        mpicc --showme:version

    - name: Build LAMMPS with OCTP plugin
      run: |
        cd lammps/src        
        make -j 8 mpi
