name: build-lammps-latest-release

on:
  push:
    branches: [ "master", "feature/github_actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout OCTP
      uses: actions/checkout@v4
      with:
        path: octp

    - name: Checkout LAMMPS
      uses: actions/checkout@v4
      with:
        repository: lammps/lammps
        ref: stable_23Jun2022_update4
        path: lammps
      # run:
      #   cd lammps
      #   git checkout 


    # - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck